### ISSUE TITLE
Upload larger files problem

### ISSUE THREAD

**Issue by JurakZdenek** [didiatworkz/screenly-ose-monitor#55] opened 2020-12-16 08:21 UTC
Hello, i have problem with upload videos larger then approx 100mb. 
For example i using 1,2Gb MP4 video.
Iam trying in Firefox and Chrome browsers.
If I upload the video directly to the player, it will upload fine.
See gif please:
![2020-12-16_9-08-39](https://user-images.githubusercontent.com/74710914/102322667-b5e4cf80-3f7f-11eb-9ae6-c81aefce1892.gif)

Monitor info:

Monitor Version: | 3.4
-- | --
Used Screenly API: | v1.2
Server IP: | 10.101.50.9
PHP Version: | 7.3.19-1~deb10u1

**Comment by JurakZdenek** [comment] 2020-12-16 09:16
I try edit in php.ini:
post_max_size = 2048M
upload_max_filesize = 2048M
post_max_size = 2048M
memory_limit = 2048M

Unsuccessfully. Still the same.

**Comment by didiatworkz** [comment] 2020-12-16 17:06
Hello @JurakZdenek 
yes this is a half half bug 😓 
I limited the upload file size to [100MB](https://github.com/didiatworkz/screenly-ose-monitor/blob/master/assets/js/monitor.js#L156)

Normally the system indicates that the file is too large and cannot be uploaded.
I have tested this with larger files and always received a timeout from the server. So I decided not to go over 100MB.

I will test it with V4.0 that an error message appears again. - That is the real bug here.

Best
didiatworkz

**Comment by didiatworkz** [comment] 2020-12-16 17:41
Hello @JurakZdenek 
in V4.0 it was the same problem - I fixed it now so that you can see the upload is to big.
The reason behind that:
![upload](https://user-images.githubusercontent.com/18490798/102385043-a7250980-3fcd-11eb-8672-8303ae4e976a.gif)

Look at the gif... When the upload is finished you can see in the right lower corner that the screenly service stop working.
This probably happens because the API interface of screenly has problems here.

Because of this, the upload is limited.
Please upload such large files directly via the player management.

I will close this issue with this.

Best
didiatworkz

**Comment by JurakZdenek** [comment] 2020-12-16 18:23
Hello @didiatworkz , its works! I change limits (file size 2000 and timeout 600000) and i upload 200mb and 1,3gb video. screen allways blink offline - online, if i delete asset blink too. Check [video](https://jurak.cloud/index.php/s/2nZ3kw32d7ffnfy) please.

**Comment by didiatworkz** [comment] 2020-12-16 18:29
Hey @JurakZdenek 
hmm... that's interesting... 😄 
Then I will investigate this a little bit more (normally I don't use so huge files)

**Comment by JurakZdenek** [comment] 2020-12-16 18:44
This is important because nowadays FullHD video files are quite large. 10 minits is about 200mb (minimum). I have more ideas but I will create new issue on it. Good job anyway! Thank you.

**Comment by didiatworkz** [comment] 2020-12-21 19:59
Hello @JurakZdenek ,

after a few tests, I was unfortunately unable to report any success.
On which operating system are you currently running the system?

Best
didiatworkz

**Comment by JurakZdenek** [comment] 2020-12-22 10:56
> 
> 
> Hello @JurakZdenek ,
> 
> after a few tests, I was unfortunately unable to report any success.
> On which operating system are you currently running the system?
> 
> I tested it now with Rpi3, Rpi4 and Ubuntu Server 20.4.1 - On all system it was only possible to upload max 50MB
> 
> Best
> didiatworkz

Hello, have you got edited php.ini file? Monitor runing on Raspi3 and screenly is on Raspi4.

**Comment by didiatworkz** [comment] 2020-12-22 13:05
Hey,

yes I've edited the php.ini and the monitor.js files and restarted the server completely.
Hhm.. Maybe the problem is that all my screenly player are installed on RPi3 -> I will test it with a RPi4!

For the other bug: Open a new issue, please 😉

**Comment by didiatworkz** [comment] 2021-01-13 18:49
I fixed the problem now without change the php.ini -> The uploads working with the chunk function, now.

**Closed by didiatworkz** 2021-01-13 18:49 UTC
Labels: bug
